
package Interface;


import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import simuladorescalonamentojava.FIFO;
import simuladorescalonamentojava.Processo;
import simuladorescalonamentojava.ROBIN;
import simuladorescalonamentojava.SJF;


public class Tela extends javax.swing.JFrame {
    ArrayList<Processo> proc = new ArrayList<>();
    int quantum;
    Thread thread_escalonador;
    /** Creates new form Tela */
    public Tela() {
        initComponents();
        
        ROBIN fifo = new ROBIN(proc, Label_mostrarLetra, Label_mostrarProcessos, Label_mostrarTempo, SeletorQuantum.getValue());
        thread_escalonador = new Thread(fifo);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        Radio_FIFO = new javax.swing.JRadioButton();
        Radio_SJF = new javax.swing.JRadioButton();
        Radio_RR = new javax.swing.JRadioButton();
        jButtonCarregar = new javax.swing.JButton();
        jButtonExec = new javax.swing.JButton();
        Label_mostrarLetra = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelTempoAtual1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Label_mostrarProcessos = new javax.swing.JLabel();
        Label_mostrarTempo = new javax.swing.JLabel();
        SeletorQuantum = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("SIMULADOR DE ESCALONAMENTO");

        buttonGroup1.add(Radio_FIFO);
        Radio_FIFO.setText("FIFO");

        buttonGroup1.add(Radio_SJF);
        Radio_SJF.setText("SJF");

        buttonGroup1.add(Radio_RR);
        Radio_RR.setText("ROUND ROBIN ");
        Radio_RR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio_RRActionPerformed(evt);
            }
        });

        jButtonCarregar.setText("Carregar Processos");
        jButtonCarregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCarregarMouseClicked(evt);
            }
        });
        jButtonCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarregarActionPerformed(evt);
            }
        });

        jButtonExec.setText("Executar");
        jButtonExec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonExecMouseClicked(evt);
            }
        });
        jButtonExec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecActionPerformed(evt);
            }
        });

        Label_mostrarLetra.setForeground(new java.awt.Color(255, 0, 0));
        Label_mostrarLetra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_mostrarLetra.setText("-IDLE-");
        Label_mostrarLetra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        Label_mostrarLetra.setName("jLabelCPU"); // NOI18N

        jLabel3.setText("CPU");

        jLabelTempoAtual1.setText("Tempo Atual:");

        jLabel2.setText("Fila de Pronto");

        Label_mostrarProcessos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Label_mostrarTempo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SeletorQuantum.setMajorTickSpacing(1);
        SeletorQuantum.setMaximum(10);
        SeletorQuantum.setMinimum(1);
        SeletorQuantum.setPaintLabels(true);
        SeletorQuantum.setPaintTicks(true);
        SeletorQuantum.setSnapToTicks(true);
        SeletorQuantum.setValue(2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonExec)
                                .addGap(44, 44, 44)
                                .addComponent(SeletorQuantum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonCarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_mostrarLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelTempoAtual1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Label_mostrarTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(135, 135, 135))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Label_mostrarProcessos, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Radio_FIFO)
                        .addComponent(Radio_SJF)
                        .addComponent(Radio_RR))
                    .addContainerGap(439, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_mostrarLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCarregar)
                        .addGap(44, 44, 44)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTempoAtual1)
                            .addComponent(Label_mostrarTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonExec)
                            .addComponent(SeletorQuantum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)))
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_mostrarProcessos, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(138, 138, 138)
                    .addComponent(Radio_FIFO)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Radio_SJF)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Radio_RR)
                    .addContainerGap(252, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Radio_RRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio_RRActionPerformed

    }//GEN-LAST:event_Radio_RRActionPerformed

    private void jButtonCarregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCarregarMouseClicked
    
        if(thread_escalonador.isAlive() == false)
        {
            proc.clear(); 
           
            String diretorioString = System.getProperty("user.dir");
            diretorioString = diretorioString.replace("\\", "/"); 
            diretorioString += "/src/Tela/";

            Path path = Paths.get(diretorioString+"processos.txt");
            List <String> valoresProcessos = new ArrayList<>();
            try {
                valoresProcessos = Files.readAllLines(path, StandardCharsets.UTF_8);
            } catch (IOException ex) {
                Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
            }

            int tempo = 0; 
            int  cont = 0; 
           
            for(String processo : valoresProcessos)  {
               
                tempo = Integer.parseInt(processo);                
              
                String nomeProcesso = Character.toString((char)(65+cont));
                proc.add(new Processo(nomeProcesso,tempo));
                cont++;
            }
          
            Label_mostrarProcessos.setText("<html>"+proc.toString()+"<html>");
        }
    }//GEN-LAST:event_jButtonCarregarMouseClicked

    private void jButtonExecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExecMouseClicked

    }//GEN-LAST:event_jButtonExecMouseClicked

    private void jButtonExecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecActionPerformed
        
        if(Radio_FIFO.isSelected() && thread_escalonador.isAlive()==false){
            FIFO fifo = new FIFO(proc, Label_mostrarLetra, Label_mostrarProcessos, Label_mostrarTempo);
            thread_escalonador = new Thread((Runnable) fifo);
          
            thread_escalonador.start();

        }
        else if(Radio_RR.isSelected() && thread_escalonador.isAlive()==false){
            quantum = SeletorQuantum.getValue(); 
            ROBIN robin = new ROBIN(proc, Label_mostrarLetra, Label_mostrarProcessos, Label_mostrarTempo, quantum);
            thread_escalonador = new Thread(robin);
            thread_escalonador.start();

        }
        else if(Radio_SJF.isSelected() && thread_escalonador.isAlive()==false){
            SJF sjf = new SJF(proc, Label_mostrarLetra, Label_mostrarProcessos, Label_mostrarTempo);
            thread_escalonador = new Thread(sjf);
            thread_escalonador.start();

        }
    }//GEN-LAST:event_jButtonExecActionPerformed

    private void jButtonCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCarregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_mostrarLetra;
    private javax.swing.JLabel Label_mostrarProcessos;
    private javax.swing.JLabel Label_mostrarTempo;
    private javax.swing.JRadioButton Radio_FIFO;
    private javax.swing.JRadioButton Radio_RR;
    private javax.swing.JRadioButton Radio_SJF;
    private javax.swing.JSlider SeletorQuantum;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCarregar;
    private javax.swing.JButton jButtonExec;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelTempoAtual1;
    // End of variables declaration//GEN-END:variables
}
